### ISSUE TITLE
Add an `impl std::error::Error for mrml::prelude::*::Error`

### ISSUE THREAD

**Issue by LeoniePhiline** [jolimail/mrml-core#36]
Hello!

I've been using `thiserror` and stumbled upon this when trying to integrate `mrml`:

`mrml::prelude::parse::Error` and `mrml::prelude::render::Error` do not implement `std::error::Error`. That's why they cannot be simply integrated into other error frameworks which all build on the std lib's `Error` trait.

Here's how this could look like: https://docs.rs/askama_shared/0.12.2/src/askama_shared/error.rs.html#43-54 

`mrml-core` could also opt into using the `thiserror` crate.

**Comment by jdrouet** [comment]
that's a good point, I'll work on this 😉

**Comment by LeoniePhiline** [comment]
Thanks so much for taking this into consideration! :)

**Comment by LeoniePhiline** [comment]
Thanks so much! :)
