### ISSUE TITLE
Rendered attributes in random order?

### ISSUE THREAD

**Issue by LeoniePhiline** [jolimail/mrml-core#39]
I had wanted to compare rendered HTML to a fixture as part of a smoke test.

As it turns out, each time the test runs, some attributes show up in a different order, making rendered text to fixture comparison fail each time.

Why is there shuffling of attribute order happening? 

Can it be fixed in a way to make each render identical?

I noticed that you are using an elaborate test helper for comparison. Making `mod helper` public would help as a workaround, but does not seem like the right solution.

What do you think?

**Comment by jdrouet** [comment]
Right now, the default implementation used for storing the attributes is using a `HashMap`. You can still enable the `orderedmap` feature to keep the order. I'll enable it by default in the next release.
Making the `mod helper` available would probably help, you're right. Making it a crate sounds better to me though.

**Comment by LeoniePhiline** [comment]
I agree with all of that - and thank you!
